post_upgrade() {
  # Define root partitions partuuid
  PART_DEV=`findmnt / -o source -n | cut -f1 -d"["`
  PART_NAME=`echo $PART_DEV | cut -d "/" -f 3`
  ROOT_PART=$(blkid | grep "${PART_NAME}" | awk -F '"' '{print $4}')
  FSTYPE=$(blkid | grep "${PART_NAME}" | awk -F '"' '{print $10}')

  if findmnt --fstab -uno SOURCE /boot &>/dev/null && ! mountpoint -q /boot; then
    echo "WARNING: /boot appears to be a separate partition but is not mounted."
  fi

  if [ ! -f /boot/cmdline.txt ]; then
    echo "===> Installing default btrfs cmdline.txt /boot..."
    echo "rootflags=subvol=@ rootfstype=btrfs root=PARTUUID=$ROOT_PART rw rootwait loglevel=3 cpufreq.default_governor=schedutil quiet splash plymouth.ignore-serial-consoles" audit=0 > /boot/cmdline.txt
  fi

  if [ ! -f /boot/config.txt ]; then
    echo "===> Installing default config.txt to /boot..."
    echo "\
[all]
ignore_lcd=1
disable_fw_kms_setup=1
disable_audio_dither
pwm_sample_bits=20

# setup headphone detect pin
gpio=10=ip,np

# boot custom kernel
arm_64bit=1
auto_initramfs=1

[all]
dtoverlay=dwc2,dr_mode=host
dtoverlay=audremap,pins_12_13
dtparam=audio=on

[pi3]
dtoverlay=vc4-kms-v3d
dtoverlay=uconsole

[cm4]
arm_boost=1
max_framebuffers=2
dtoverlay=vc4-kms-v3d-pi4
dtoverlay=uconsole,cm4

[all]
# whatever you need
" > /boot/config.txt
  fi
}

post_remove() {
  rm -f boot/initramfs8
}


post_install() {
  # Define root partitions partuuid
  PART_DEV=`findmnt / -o source -n | cut -f1 -d"["`
  PART_NAME=`echo $PART_DEV | cut -d "/" -f 3`
  ROOT_PART=$(blkid | grep "${PART_NAME}" | awk -F '"' '{print $4}')
  FSTYPE=$(blkid | grep "${PART_NAME}" | awk -F '"' '{print $10}')

  if findmnt --fstab -uno SOURCE /boot &>/dev/null && ! mountpoint -q /boot; then
    echo "WARNING: /boot appears to be a separate partition but is not mounted."
  fi

  if [ ! -f /boot/cmdline.txt ]; then
    echo "===> Installing default btrfs cmdline.txt /boot..."
    echo "rootflags=subvol=@ rootfstype=btrfs root=PARTUUID=$ROOT_PART rw rootwait loglevel=3 cpufreq.default_governor=schedutil quiet splash plymouth.ignore-serial-consoles" > /boot/cmdline.txt
  fi
  
  if [ ! -f /boot/config.txt ]; then
    echo "===> Installing default config.txt to /boot..."
    echo "\
[all]
ignore_lcd=1
disable_fw_kms_setup=1
disable_audio_dither
pwm_sample_bits=20

# setup headphone detect pin
gpio=10=ip,np

# boot custom kernel
#kernel=Image.gz
arm_64bit=1
#initramfs initramfs-linux.img followkernel

[all]
dtoverlay=dwc2,dr_mode=host
dtoverlay=audremap,pins_12_13
dtparam=audio=on

[pi3]
dtoverlay=vc4-kms-v3d
dtoverlay=uconsole

[cm4]
arm_boost=1
max_framebuffers=2
dtoverlay=vc4-kms-v3d-pi4
dtoverlay=uconsole,cm4

[all]
# whatever you need
" > /boot/config.txt
  fi
}