#!/bin/bash

function tip {
    echo "use mmcli -L to see 4G modem or not"
}

function enable4g {
    echo "Power on 4G module on uConsole cm4"
    gpioset -c 0 24=1 &
    sleep 0.1
    kill $!
    gpioset -c 0 15=1 &
    sleep 5
    kill $!
    gpioset -c 0 15=0 &
    sleep 0.1
    kill $!
    
    echo "waiting..."
    sleep 13
    echo "done"
}

function disable4g {
    echo "Power off 4G module"
    gpioset -c 0 24=0 &
    sleep 3
    kill $!
    gpioset -c 0 24=1 &
    sleep 3
    kill $!
    gpioset -c 0 24=0 &
    sleep 0.1
    kill $!
    
    sleep 20
    echo "Done"
}

case "$1" in
    enable)
        enable4g
        tip
        ;;
    disable)
        disable4g
        tip
        ;;
    *)
        echo "Invalid argument: $1"
        echo "Usage: $0 enable/disable"
        exit 4
        ;;
esac
