[profile]
# Profile for uConsole CM4
name=uconsole-cm4
target=aarch64
board=raspberrypi-4
edition=minimal
rootfs=manjaro-arm
packages=(
    base
    linux-clockworkpi-uc4
    firmware-raspberrypi
    wireless-regdb
    manjaro-arm-tools
    u-boot-raspberrypi
)
