post_install() {
    # Enable services
    systemctl enable stop-dmesg.service

    # Edit mkinitcpio.conf
    echo "Editing mkinitcpio.conf..."
    sed -i s/"MODULES=()"/"MODULES=(vc4)"/g /etc/mkinitcpio.conf

    # Edit cmdline.txt
    echo "Editing cmdline.txt..."
    echo "rootflags=subvol=@ root=/dev/mmcblk0p2 rootfstype=btrfs console=tty3 rw rootwait loglevel=3 cpufreq.default_governor=schedutil" > /boot/cmdline.txt
    #sed -i s!"plymouth.enable=0"!"quiet splash plymouth.ignore-serial-consoles"!g /boot/cmdline.txt

    # Edit config.txt
    #echo "Editing config.txt..."
    #echo "disable_splash=1" >> /boot/config.txt

    # Disable AMS on installs with kwin
    if [ -f /usr/bin/kwin_x11 ]; then
        echo "KWIN_DRM_NO_AMS=1" >> /etc/environment
    fi
}

post_upgrade() {
    # Disable AMS on installs with kwin
    if [[ $(grep "KWIN_DRM_NO_AMS=1" /etc/environment) ]]; then
        echo "AMS already disabled..."
    elif [ -f /usr/bin/kwin_x11 ]; then
        echo "KWIN_DRM_NO_AMS=1" >> /etc/environment
        echo "Disabling AMS..."
    fi
}
