name: Build and Release NixOS-WSL installer
run-name: ${{ github.actor }} is building and releasing NixOS-WSL 🚀
# write a code about action workflow be trigger by manual other than push.
#on: [push]
on:
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare 🚀
    runs-on: self-hosted
    container:
      image: manjarolinux/build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: test
        run: |
          # cd /__w/linux-uconsole-rpi4/linux-uconsole-rpi4
          # makepkg -s
          ls

      # - name: Pull Manjaro/build
      #   uses: cachix/install-nix-action@v22
      #   with:
      #     extra_nix_config: 'access-tokens = github.com=${{ github.token }}'

      # - name: Make package
      #   id: version
      #   run: |
      #     TAG_COUNT=$(git rev-list --tags --no-walk --count)                                                                 # Count all tags
      #     COMMIT_COUNT=$(git rev-list --use-bitmap-index --count $(git rev-list --tags --no-walk --max-count=1)..HEAD)       # Count all commits since the last tag
      #     NIXOS_VERSION=$(nix-instantiate --eval -E '(import ./.).inputs.nixpkgs.lib.version' | sed -E 's/"(.+\...).*"/\1/') # Get NixOS version from nixpkgs
      #     NIXOS_VERSION_MS=$(echo $NIXOS_VERSION | sed -E 's/\.0*(.+)/\.\1/')                                                # Remove the leading 0 from the minor version (if it exists)
      #     NIXOS_WSL_VERSION=${NIXOS_VERSION_MS}.${TAG_COUNT}.${COMMIT_COUNT}                                                 # Compose the NixOS-WSL version number
      #     echo "version=$NIXOS_WSL_VERSION" >> $GITHUB_OUTPUT

      # - name: Upload installer 📤
      #   uses: actions/upload-artifact@v3.1.2
      #   with:
      #     name: installer
      #     path: result/tarball/nixos-wsl-installer.tar.gz*

      # - uses: stefanzweifel/git-auto-commit-action@v4.16.0
      #   if: ${{ success() }}
      #   with:
      #     commit_message: 'automation: update flake.lock'
      #     file_pattern: 'flake.lock'

      # - name: Create release 📢
      #   id: create_release
      #   uses: ncipollo/release-action@v1.12.0
      #   with:
      #     name: nixos-wsl-installer.tar.gz
      #     allowUpdates: true
      #     prerelease: false
      #     tag: ${{ steps.version.outputs.version }}
      #     #commit: 23.05
      #     replacesArtifacts: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     artifacts: result/tarball/nixos-wsl-installer.tar.gz*
